### PR TITLE
 Fix OBJECTS_REJ build error & warning + silhouette incompatibility

### LINKED ISSUE #323: OBJECTS_REJ doesn't build + silhouette incompatibility
When OBJECTS_REJ is enabled, the game doesn't build due to using the wrong ucode in switch_ucode().

There is also a build warning in cur_obj_update().

Also, Mario doesn't render when both OBJECTS_REJ and SILHOUETTE are enabled, due to Mario & the silhouette not being forced to the .rej layer

### PR DESCRIPTION
**Pull request by Arceveti**
Fixes #323

### CODE REVIEW

File: src/game/rendering_graph_node.c [hunk 1]
```diff
@@ -248,7 +248,7 @@ void switch_ucode(s32 ucode) {
     switch (ucode) {
         default: // GRAPH_NODE_UCODE_DEFAULT
         case GRAPH_NODE_UCODE_DEFAULT:
-            gSPLoadUcodeL(gDisplayListHead++, gspF3DZEX2_PosLight_fifo); // F3DZEX2_PosLight
+            gSPLoadUcodeL(gDisplayListHead++, gspF3DZEX2_NoN_PosLight_fifo); // F3DZEX2_PosLight
```
Comment (thecozies) [inline src/game/rendering_graph_node.c:251]: wat

Comment (Arceveti) [reply src/game/rendering_graph_node.c:251]: That was because of [https://github.com/HackerSM64/HackerSM64/commit/475e039f8acd2d240eab9110597e4d9ecf0609c0](https://github.com/HackerSM64/HackerSM64/commit/475e039f8acd2d240eab9110597e4d9ecf0609c0)

**Review by thecozies — APPROVED** [review]
