### PR TITLE
Fix end cake screen crash & flickering

### LINKED ISSUE #600: End cake screen crashes on console when entering via debug level select
End Cake Screen
image

### PR DESCRIPTION
**Pull request by Arceveti**
Fixes #600

### CODE REVIEW

File: levels/ending/geo.c [hunk 1]
```diff
@@ -21,9 +21,7 @@ const GeoLayout ending_geo_area_1[] = {
       GEO_OPEN_NODE(),
          GEO_NODE_ORTHO(100),
          GEO_OPEN_NODE(),
-#ifdef VERSION_EU
-            GEO_BACKGROUND_COLOR(0x0001),
-#endif
+            GEO_BACKGROUND_COLOR(GPACK_RGBA5551(0, 0, 0, 1)),
```
Comment (gheskett) [inline levels/ending/geo.c:24]: Why wasn't this in Shindou? 🤔

**Review by gheskett — APPROVED** [review]

File: levels/ending/geo.c (hunk 1 above)
Comment (Arceveti) [reply levels/ending/geo.c:24]: This was probably originally found in EU when they were making the end cake screen change with the selected language, and since it didn't change in shindou they probably just reverted all of the leveldata. Just a guess though.
